---

- hosts: all
  become: true
  tasks:

  - name: install apache package to target
    apt: 
      name: nginx
  - name: start nginx server
    service: 
      name: nginx
      state: started
 - name: install nodejs using shell
    shell: |
      curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash - && sudo apt-get install -y nodejs